In [1]:
import rebound
import reboundx
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

pd.set_option('display.precision', 20)

In [27]:
heartbeat_column_names = [
    "t", "walltime", "N", "total_mass", 
    "ang_mom_x", "ang_mom_y", "ang_mom_z", "energy", 
    "p3_m", "p3_r", "p3_x", "p3_y", "p3_z", 
    "p3_vx", "p3_vy", "p3_vz"
]

# Read the files
heartbeat_embryo_3 = pd.read_csv(
    "diagnose_TRACE/heartbeat_particle_3_2_IAS15.txt", 
    names=heartbeat_column_names, 
    header=None
)

heartbeat_101 = pd.read_csv(
    "diagnose_TRACE/heartbeat_particle_101.txt", 
    names=heartbeat_column_names, 
    header=None
)

# Filter the first DataFrame
heartbeat_from_begin = heartbeat_embryo_3[heartbeat_embryo_3['t'] >= 83].copy()
heartbeat_101 = heartbeat_101[heartbeat_101['t'] >= 83]
# Drop 'walltime' from both DataFrames in-place
heartbeat_from_begin.drop(columns=['walltime'], inplace=True)
heartbeat_101.drop(columns=['walltime'], inplace=True)

In [28]:
t_collision = 8.318553e+01

In [29]:
# Ensure they are the same length before comparing
min_length = min(len(heartbeat_from_begin), len(heartbeat_101))
if len(heartbeat_from_begin) != len(heartbeat_101):
    print(f"Warning: Row counts differ ({len(heartbeat_from_begin)} vs {len(heartbeat_101)}). Truncating to {min_length} rows to compare.")
    heartbeat_from_begin = heartbeat_from_begin.iloc[:min_length]
    heartbeat_101 = heartbeat_101.iloc[:min_length]

# FIX: Force exact index alignment (0 to min_length - 1) on both before comparing
heartbeat_from_begin = heartbeat_from_begin.reset_index(drop=True)
heartbeat_101 = heartbeat_101.reset_index(drop=True)

# Compare ONLY the 'energy' column
energy_differences = heartbeat_from_begin['energy'].compare(heartbeat_101['energy'])

if energy_differences.empty:
    print("No differences found in the energy column. The files match perfectly!")
else:
    print(f"Found differences in {len(energy_differences)} rows in the energy column.")
    
    # List the rows where energy values differ
    diff_row_indices = energy_differences.index.tolist()
    print(f"Rows with energy differences: {diff_row_indices}\n")
    energy_differences['delta'] = energy_differences['self'] - energy_differences['other']
    # Display the side-by-side comparison for the energy column
    print("Detailed Energy Differences (self = heartbeat_from_begin, other = heartbeat_101):")
    print(energy_differences)

Warning: Row counts differ (612 vs 452). Truncating to 452 rows to compare.
No differences found in the energy column. The files match perfectly!

In [30]:
x_differences = heartbeat_from_begin['p3_x'].compare(heartbeat_101['p3_x'])

if x_differences.empty:
    print("No differences found in the X position. The files match perfectly!")
else:
    print(f"Found differences in {len(x_differences)} rows in the X position (p3_x).\n")
    
    # List the rows where X values differ
    diff_row_indices = x_differences.index.tolist()
    print(f"Rows with X differences: {diff_row_indices}\n")
    
    # Add a column showing the exact mathematical difference (delta)
    x_differences['delta'] = x_differences['self'] - x_differences['other']
    
    # Display the side-by-side comparison for the X column
    print("Detailed X Position Differences (Full Precision):")
    print(x_differences)

No differences found in the X position. The files match perfectly!

In [31]:
x_differences = heartbeat_from_begin['p3_z'].compare(heartbeat_101['p3_z'])

if x_differences.empty:
    print("No differences found in the X position. The files match perfectly!")
else:
    print(f"Found differences in {len(x_differences)} rows in the X position (p3_z).\n")
    
    # List the rows where X values differ
    diff_row_indices = x_differences.index.tolist()
    print(f"Rows with X differences: {diff_row_indices}\n")
    
    # Add a column showing the exact mathematical difference (delta)
    x_differences['delta'] = x_differences['self'] - x_differences['other']
    
    # Display the side-by-side comparison for the X column
    print("Detailed X Position Differences (Full Precision):")
    print(x_differences)

No differences found in the X position. The files match perfectly!

In [32]:
x_differences = heartbeat_from_begin['p3_vx'].compare(heartbeat_101['p3_vx'])

if x_differences.empty:
    print("No differences found in the X position. The files match perfectly!")
else:
    print(f"Found differences in {len(x_differences)} rows in the X position (p3_vx).\n")
    
    # List the rows where X values differ
    diff_row_indices = x_differences.index.tolist()
    print(f"Rows with X differences: {diff_row_indices}\n")
    
    # Add a column showing the exact mathematical difference (delta)
    x_differences['delta'] = x_differences['self'] - x_differences['other']
    
    # Display the side-by-side comparison for the X column
    print("Detailed X Position Differences (Full Precision):")
    print(x_differences)

No differences found in the X position. The files match perfectly!

In [33]:
x_differences = heartbeat_from_begin['p3_vy'].compare(heartbeat_101['p3_vy'])

if x_differences.empty:
    print("No differences found in the X position. The files match perfectly!")
else:
    print(f"Found differences in {len(x_differences)} rows in the X position (p3_vy).\n")
    
    # List the rows where X values differ
    diff_row_indices = x_differences.index.tolist()
    print(f"Rows with X differences: {diff_row_indices}\n")
    
    # Add a column showing the exact mathematical difference (delta)
    x_differences['delta'] = x_differences['self'] - x_differences['other']
    
    # Display the side-by-side comparison for the X column
    print("Detailed X Position Differences (Full Precision):")
    print(x_differences)

No differences found in the X position. The files match perfectly!

In [34]:
x_differences = heartbeat_from_begin['p3_vz'].compare(heartbeat_101['p3_vz'])

if x_differences.empty:
    print("No differences found in the X position. The files match perfectly!")
else:
    print(f"Found differences in {len(x_differences)} rows in the X position (p3_vz).\n")
    
    # List the rows where X values differ
    diff_row_indices = x_differences.index.tolist()
    print(f"Rows with X differences: {diff_row_indices}\n")
    
    # Add a column showing the exact mathematical difference (delta)
    x_differences['delta'] = x_differences['self'] - x_differences['other']
    
    # Display the side-by-side comparison for the X column
    print("Detailed X Position Differences (Full Precision):")
    print(x_differences)

No differences found in the X position. The files match perfectly!

In [35]:
print(heartbeat_from_begin['energy'])

0     -0.00059210399999999998
1     -0.00059210399999999998
2     -0.00059210399999999998
3     -0.00059210399999999998
4     -0.00059210399999999998
                ...
447   -0.00059210120000000000
448   -0.00059210120000000000
449   -0.00059210120000000000
450   -0.00059210120000000000
451   -0.00059210120000000000
Name: energy, Length: 452, dtype: float64

In [36]:
print(heartbeat_101['energy'])

0     -0.00059210399999999998
1     -0.00059210399999999998
2     -0.00059210399999999998
3     -0.00059210399999999998
4     -0.00059210399999999998
                ...
447   -0.00059210120000000000
448   -0.00059210120000000000
449   -0.00059210120000000000
450   -0.00059210120000000000
451   -0.00059210120000000000
Name: energy, Length: 452, dtype: float64

In [37]:
heartbeat_101

,t,N,total_mass,ang_mom_x,ang_mom_y,ang_mom_z,energy,p3_m,p3_r,p3_x,p3_y,p3_z,p3_vx,p3_vy,p3_vz
0,83.01379000000000019099,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,-0.02212601000000000151,-0.40392800000000000926,0.00419862399999999976,9.94158900000000045338,-0.45017350000000000421,0.01736860999999999960
1,83.03018000000000142791,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,0.13825670000000001014,-0.37908340000000001480,0.00414286800000000007,9.36275799999999946976,3.44562500000000015987,-0.02413289999999999880
2,83.04661000000000115051,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,0.27693919999999999648,-0.29360740000000001837,0.00342503499999999989,7.28391900000000003246,6.81389800000000001035,-0.06202650999999999998
3,83.08007000000000630280,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,0.40701640000000000041,0.00265863099999999984,0.00049046550000000000,0.08643518000000000034,9.89122799999999990916,-0.10339470000000000605
4,83.09627999999999303782,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,0.37767250000000002208,0.15873529999999999585,-0.00118013300000000009,-3.64915099999999981151,9.12541200000000074510,-0.10013769999999999616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,90.37868000000000279215,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,-0.38981419999999999959,-0.13912320000000000242,0.00107148000000000009,3.42898199999999997445,-9.12739499999999992497,0.09847614999999999841
448,90.39507999999999299234,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,-0.30600329999999997810,-0.27468710000000001736,0.00256603599999999984,6.67578500000000030212,-7.19367000000000000881,0.08147342000000000473
449,90.41100000000000136424,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,-0.18036269999999998692,-0.36682920000000002192,0.00364860299999999983,8.91986200000000017951,-4.23020399999999963114,0.05276242999999999905
450,90.42806000000000210548,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,-0.01742847000000000146,-0.40639370000000002436,0.00421933200000000012,9.91459799999999980002,-0.33311960000000001569,0.01310537999999999981
451,90.44450000000000500222,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,0.14265859999999999652,-0.37983770000000000033,0.00409804900000000031,9.29900899999999985823,3.52534999999999998366,-0.02771374999999999880

In [38]:
heartbeat_from_begin

,t,N,total_mass,ang_mom_x,ang_mom_y,ang_mom_z,energy,p3_m,p3_r,p3_x,p3_y,p3_z,p3_vx,p3_vy,p3_vz
0,83.01379000000000019099,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,-0.02212601000000000151,-0.40392800000000000926,0.00419862399999999976,9.94158900000000045338,-0.45017350000000000421,0.01736860999999999960
1,83.03018000000000142791,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,0.13825670000000001014,-0.37908340000000001480,0.00414286800000000007,9.36275799999999946976,3.44562500000000015987,-0.02413289999999999880
2,83.04661000000000115051,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,0.27693919999999999648,-0.29360740000000001837,0.00342503499999999989,7.28391900000000003246,6.81389800000000001035,-0.06202650999999999998
3,83.08007000000000630280,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,0.40701640000000000041,0.00265863099999999984,0.00049046550000000000,0.08643518000000000034,9.89122799999999990916,-0.10339470000000000605
4,83.09627999999999303782,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,0.37767250000000002208,0.15873529999999999585,-0.00118013300000000009,-3.64915099999999981151,9.12541200000000074510,-0.10013769999999999616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,90.37868000000000279215,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,-0.38981419999999999959,-0.13912320000000000242,0.00107148000000000009,3.42898199999999997445,-9.12739499999999992497,0.09847614999999999841
448,90.39507999999999299234,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,-0.30600329999999997810,-0.27468710000000001736,0.00256603599999999984,6.67578500000000030212,-7.19367000000000000881,0.08147342000000000473
449,90.41100000000000136424,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,-0.18036269999999998692,-0.36682920000000002192,0.00364860299999999983,8.91986200000000017951,-4.23020399999999963114,0.05276242999999999905
450,90.42806000000000210548,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,-0.01742847000000000146,-0.40639370000000002436,0.00421933200000000012,9.91459799999999980002,-0.33311960000000001569,0.01310537999999999981
451,90.44450000000000500222,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,0.14265859999999999652,-0.37983770000000000033,0.00409804900000000031,9.29900899999999985823,3.52534999999999998366,-0.02771374999999999880

In [39]:
heartbeat_101

,t,N,total_mass,ang_mom_x,ang_mom_y,ang_mom_z,energy,p3_m,p3_r,p3_x,p3_y,p3_z,p3_vx,p3_vy,p3_vz
0,83.01379000000000019099,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,-0.02212601000000000151,-0.40392800000000000926,0.00419862399999999976,9.94158900000000045338,-0.45017350000000000421,0.01736860999999999960
1,83.03018000000000142791,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,0.13825670000000001014,-0.37908340000000001480,0.00414286800000000007,9.36275799999999946976,3.44562500000000015987,-0.02413289999999999880
2,83.04661000000000115051,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,0.27693919999999999648,-0.29360740000000001837,0.00342503499999999989,7.28391900000000003246,6.81389800000000001035,-0.06202650999999999998
3,83.08007000000000630280,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,0.40701640000000000041,0.00265863099999999984,0.00049046550000000000,0.08643518000000000034,9.89122799999999990916,-0.10339470000000000605
4,83.09627999999999303782,31,1.000008000000000008,0.0000001009667,0.00000003157216,0.00002642041,-0.00059210399999999998,0.0000001849266,0.00002060028,0.37767250000000002208,0.15873529999999999585,-0.00118013300000000009,-3.64915099999999981151,9.12541200000000074510,-0.10013769999999999616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,90.37868000000000279215,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,-0.38981419999999999959,-0.13912320000000000242,0.00107148000000000009,3.42898199999999997445,-9.12739499999999992497,0.09847614999999999841
448,90.39507999999999299234,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,-0.30600329999999997810,-0.27468710000000001736,0.00256603599999999984,6.67578500000000030212,-7.19367000000000000881,0.08147342000000000473
449,90.41100000000000136424,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,-0.18036269999999998692,-0.36682920000000002192,0.00364860299999999983,8.91986200000000017951,-4.23020399999999963114,0.05276242999999999905
450,90.42806000000000210548,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,-0.01742847000000000146,-0.40639370000000002436,0.00421933200000000012,9.91459799999999980002,-0.33311960000000001569,0.01310537999999999981
451,90.44450000000000500222,30,1.000008000000000008,0.0000001009622,0.00000003156431,0.00002642040,-0.00059210120000000000,0.0000001849266,0.00002060028,0.14265859999999999652,-0.37983770000000000033,0.00409804900000000031,9.29900899999999985823,3.52534999999999998366,-0.02771374999999999880