In [31]:
import rebound
import reboundx
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

pd.set_option('display.precision', 20)

In [32]:
heartbeat_column_names = [
    "t", "walltime", "N", "total_mass", 
    "ang_mom_x", "ang_mom_y", "ang_mom_z", "energy", 
    "p3_m", "p3_r", "p3_x", "p3_y", "p3_z", 
    "p3_vx", "p3_vy", "p3_vz"
]

# Read the files
heartbeat_embryo_3 = pd.read_csv(
    "diagnose_TRACE/heartbeat_particle.txt", 
    names=heartbeat_column_names, 
    header=None
)

heartbeat_841 = pd.read_csv(
    "diagnose_TRACE/heartbeat_particle_841.txt", 
    names=heartbeat_column_names, 
    header=None
)

# Filter the first DataFrame
heartbeat_from_begin = heartbeat_embryo_3[heartbeat_embryo_3['t'] > 691.232].copy()

# Drop 'walltime' from both DataFrames in-place
heartbeat_from_begin.drop(columns=['walltime'], inplace=True)
heartbeat_841.drop(columns=['walltime'], inplace=True)

In [33]:
# Ensure they are the same length before comparing
min_length = min(len(heartbeat_from_begin), len(heartbeat_841))
if len(heartbeat_from_begin) != len(heartbeat_841):
    print(f"Warning: Row counts differ ({len(heartbeat_from_begin)} vs {len(heartbeat_841)}). Truncating to {min_length} rows to compare.")
    heartbeat_from_begin = heartbeat_from_begin.iloc[:min_length]
    heartbeat_841 = heartbeat_841.iloc[:min_length]

# FIX: Force exact index alignment (0 to min_length - 1) on both before comparing
heartbeat_from_begin = heartbeat_from_begin.reset_index(drop=True)
heartbeat_841 = heartbeat_841.reset_index(drop=True)

# Compare ONLY the 'energy' column
energy_differences = heartbeat_from_begin['energy'].compare(heartbeat_841['energy'])

if energy_differences.empty:
    print("No differences found in the energy column. The files match perfectly!")
else:
    print(f"Found differences in {len(energy_differences)} rows in the energy column.")
    
    # List the rows where energy values differ
    diff_row_indices = energy_differences.index.tolist()
    print(f"Rows with energy differences: {diff_row_indices}\n")
    
    # Display the side-by-side comparison for the energy column
    print("Detailed Energy Differences (self = heartbeat_from_begin, other = heartbeat_841):")
    print(energy_differences)

Warning: Row counts differ (15168 vs 610). Truncating to 610 rows to compare.
Found differences in 508 rows in the energy column.
Rows with energy differences: [2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 23, 24, 25, 26, 31, 35, 39, 40, 42, 43, 53, 54, 55, 56, 57, 58, 59, 61, 62, 75, 76, 79, 80, 82, 83, 84, 86, 88, 89, 91, 92, 93, 94, 95, 96, 97, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 119, 124, 125, 126, 127, 128, 129, 130, 131, 132, 135, 136, 137, 138, 139, 141, 142, 149, 150, 155, 163, 165, 166, 169, 170, 171, 176, 177, 179, 180, 182, 183, 191, 192, 193, 194, 195, 196, 197, 198, 199, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 217, 218, 225, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609]

Detailed Energy Differences (self = heartbeat_from_begin, other = heartbeat_841):
                       self                   other
2   -0.00059244009999999999 -0.00059243999999999996
3   -0.00059244009999999999 -0.00059243999999999996
5   -0.00059244009999999999 -0.00059243999999999996
6   -0.00059244020000000003 -0.00059243999999999996
7   -0.00059244009999999999 -0.00059243999999999996
..                      ...                     ...
605 -0.00059244639999999997 -0.00059244759999999995
606 -0.00059244639999999997 -0.00059244759999999995
607 -0.00059244639999999997 -0.00059244759999999995
608 -0.00059244639999999997 -0.00059244759999999995
609 -0.00059244639999999997 -0.00059244759999999995

[508 rows x 2 columns]

In [34]:
energy_differences

                       self                   other
2   -0.00059244009999999999 -0.00059243999999999996
3   -0.00059244009999999999 -0.00059243999999999996
5   -0.00059244009999999999 -0.00059243999999999996
6   -0.00059244020000000003 -0.00059243999999999996
7   -0.00059244009999999999 -0.00059243999999999996
..                      ...                     ...
605 -0.00059244639999999997 -0.00059244759999999995
606 -0.00059244639999999997 -0.00059244759999999995
607 -0.00059244639999999997 -0.00059244759999999995
608 -0.00059244639999999997 -0.00059244759999999995
609 -0.00059244639999999997 -0.00059244759999999995

[508 rows x 2 columns]

In [35]:
heartbeat_841

,t,N,total_mass,ang_mom_x,ang_mom_y,ang_mom_z,energy,p3_m,p3_r,p3_x,p3_y,p3_z,p3_vx,p3_vy,p3_vz
0,691.23289999999997235136,31,1.00000899999999992573,0.000000003733960,-0.00000001006736,0.00003104342,-0.00059243999999999996,0.0000003063898,0.00002437613,0.18054339999999999278,-0.41759659999999998448,-0.00381818999999999995,8.59754700000000049442,3.61065399999999980807,-0.06757428999999999519
1,691.24929999999994834070,31,1.00000899999999992573,0.000000003733960,-0.00000001006736,0.00003104342,-0.00059243999999999996,0.0000003063898,0.00002437613,0.30914079999999999337,-0.33600609999999997424,-0.00469480199999999966,6.90434899999999984743,6.21813400000000005008,-0.03812987999999999794
2,691.26580000000001291482,31,1.00000899999999992573,0.000000003733960,-0.00000001006736,0.00003104342,-0.00059243999999999996,0.0000003063898,0.00002437613,0.40343980000000001507,-0.21709249999999999381,-0.00505031700000000035,4.46607800000000043639,8.11180599999999962790,-0.00477871300000000040
3,691.28219999999998890416,31,1.00000899999999992573,0.000000003733960,-0.00000001006736,0.00003104342,-0.00059243999999999996,0.0000003063898,0.00002437613,0.45340989999999997684,-0.07429541000000000617,-0.00485076199999999978,1.56172599999999994758,9.10025000000000083844,0.02878591999999999956
4,691.29859999999996489350,31,1.00000899999999992573,0.000000003733960,-0.00000001006736,0.00003104342,-0.00059243999999999996,0.0000003063898,0.00002437613,0.45396839999999999415,0.07661866999999999983,-0.00412247499999999958,-1.49133099999999996221,9.09293599999999990757,0.05898108999999999991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,701.17809999999997216946,30,1.00000899999999992573,0.000000003732726,-0.00000001006750,0.00003104342,-0.00059244759999999995,0.0000003063898,0.00002437613,0.33068629999999998859,0.32191399999999997794,-0.00160922100000000009,-6.42928099999999957959,6.56807099999999977058,0.09800245999999999957
606,701.19449999999994815880,30,1.00000899999999992573,0.000000003732726,-0.00000001006750,0.00003104342,-0.00059244759999999995,0.0000003063898,0.00002437613,0.20910000000000000808,0.41060390000000002164,0.00005938238000000000,-8.23080599999999940053,4.12264199999999991775,0.10317160000000000220
607,701.21100000000001273293,30,1.00000899999999992573,0.000000003732726,-0.00000001006750,0.00003104342,-0.00059244759999999995,0.0000003063898,0.00002437613,0.06492939000000000349,0.45490639999999998855,0.00172136699999999991,-9.15090499999999984482,1.21424099999999990374,0.09718032999999999533
608,701.22739999999998872227,30,1.00000899999999992573,0.000000003732726,-0.00000001006750,0.00003104342,-0.00059244759999999995,0.0000003063898,0.00002437613,-0.08628956000000000126,0.44963859999999999939,0.00319550999999999993,-9.07749399999999972977,-1.85480200000000006177,0.08048839000000000687
609,701.24379999999996471161,30,1.00000899999999992573,0.000000003732726,-0.00000001006750,0.00003104342,-0.00059244759999999995,0.0000003063898,0.00002437613,-0.22797290000000000609,0.39485779999999998102,0.00431743600000000002,-7.99746299999999976649,-4.75396899999999966724,0.05468475999999999893

In [36]:
x_differences = heartbeat_from_begin['p3_x'].compare(heartbeat_841['p3_x'])

if x_differences.empty:
    print("No differences found in the X position. The files match perfectly!")
else:
    print(f"Found differences in {len(x_differences)} rows in the X position (p3_x).\n")
    
    # List the rows where X values differ
    diff_row_indices = x_differences.index.tolist()
    print(f"Rows with X differences: {diff_row_indices}\n")
    
    # Add a column showing the exact mathematical difference (delta)
    x_differences['delta'] = x_differences['self'] - x_differences['other']
    
    # Display the side-by-side comparison for the X column
    print("Detailed X Position Differences (Full Precision):")
    print(x_differences)

# Reset pandas display back to default when done
pd.reset_option('display.precision')

Found differences in 585 rows in the X position (p3_x).

Rows with X differences: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 65, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 88, 89, 90, 91, 92, 93, 94, 95, 96, 98, 99, 100, 101, 102, 103, 104, 105, 107, 108, 109, 110, 111, 112, 113, 114, 115, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 145, 146, 147, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609]

Detailed X Position Differences (Full Precision):
                       self                   other                   delta
4    0.45396829999999999128  0.45396839999999999415 -0.00000010000000000288
5    0.40534140000000001836  0.40534150000000002123 -0.00000010000000000288
6    0.31292100000000000470  0.31292110000000000758 -0.00000010000000000288
7    0.18667759999999999909  0.18667770000000000197 -0.00000010000000000288
8    0.04018760999999999861  0.04018773999999999957 -0.00000013000000000096
..                      ...                     ...                     ...
605  0.33070030000000000259  0.33068629999999998859  0.00001400000000001400
606  0.20911879999999999358  0.20910000000000000808  0.00001879999999998549
607  0.06495130999999999821  0.06492939000000000349  0.00002191999999999472
608 -0.08626683000000000268 -0.08628956000000000126  0.00002272999999999858
609 -0.22795229999999999659 -0.22797290000000000609  0.00002060000000000950

[585 rows x 3 columns]

In [37]:
x_differences = heartbeat_from_begin['p3_y'].compare(heartbeat_841['p3_y'])
if x_differences.empty:
    print("No differences found in the X position. The files match perfectly!")
else:
    print(f"Found differences in {len(x_differences)} rows in the X position (p3_y).\n")
    
    # List the rows where X values differ
    diff_row_indices = x_differences.index.tolist()
    print(f"Rows with X differences: {diff_row_indices}\n")
    
    # Add a column showing the exact mathematical difference (delta)
    x_differences['delta'] = x_differences['self'] - x_differences['other']
    
    # Display the side-by-side comparison for the X column
    print("Detailed X Position Differences (Full Precision):")
    print(x_differences)

# Reset pandas display back to default when done
pd.reset_option('display.precision')

Found differences in 586 rows in the X position (p3_y).

Rows with X differences: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 16, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 37, 38, 41, 42, 43, 44, 45, 46, 47, 49, 50, 51, 54, 55, 56, 57, 59, 60, 61, 62, 64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 112, 113, 114, 115, 116, 117, 118, 119, 121, 122, 123, 124, 125, 126, 127, 128, 129, 131, 132, 133, 134, 135, 136, 137, 138, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609]

Detailed X Position Differences (Full Precision):
         self     other         delta
2   -0.217092 -0.217092  1.000000e-07
3   -0.074295 -0.074295  8.000000e-08
4    0.076619  0.076619  9.000000e-08
5    0.219244  0.219244  1.000000e-07
6    0.338185  0.338185  1.000000e-07
..        ...       ...           ...
605  0.321902  0.321914 -1.220000e-05
606  0.410597  0.410604 -6.900000e-06
607  0.454906  0.454906 -5.000000e-07
608  0.449645  0.449639  6.600000e-06
609  0.394871  0.394858  1.320000e-05

[586 rows x 3 columns]

In [38]:
x_differences = heartbeat_from_begin['p3_z'].compare(heartbeat_841['p3_z'])

if x_differences.empty:
    print("No differences found in the X position. The files match perfectly!")
else:
    print(f"Found differences in {len(x_differences)} rows in the X position (p3_z).\n")
    
    # List the rows where X values differ
    diff_row_indices = x_differences.index.tolist()
    print(f"Rows with X differences: {diff_row_indices}\n")
    
    # Add a column showing the exact mathematical difference (delta)
    x_differences['delta'] = x_differences['self'] - x_differences['other']
    
    # Display the side-by-side comparison for the X column
    print("Detailed X Position Differences (Full Precision):")
    print(x_differences)

# Reset pandas display back to default when done
pd.reset_option('display.precision')

Found differences in 591 rows in the X position (p3_z).

Rows with X differences: [3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 57, 58, 60, 61, 62, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609]

Detailed X Position Differences (Full Precision):
         self     other         delta
3   -0.004851 -0.004851 -1.000000e-09
4   -0.004122 -0.004122  1.000000e-09
5   -0.002947 -0.002947  1.000000e-09
6   -0.001454 -0.001454  1.000000e-09
7    0.000197  0.000197  5.000000e-10
..        ...       ...           ...
605 -0.001609 -0.001609 -1.140000e-07
606  0.000059  0.000059 -1.979200e-07
607  0.001721  0.001721 -2.560000e-07
608  0.003195  0.003196 -2.750000e-07
609  0.004317  0.004317 -2.540000e-07

[591 rows x 3 columns]

In [39]:
x_differences = heartbeat_from_begin['p3_vx'].compare(heartbeat_841['p3_vx'])

if x_differences.empty:
    print("No differences found in the X position. The files match perfectly!")
else:
    print(f"Found differences in {len(x_differences)} rows in the X position (p3_vx).\n")
    
    # List the rows where X values differ
    diff_row_indices = x_differences.index.tolist()
    print(f"Rows with X differences: {diff_row_indices}\n")
    
    # Add a column showing the exact mathematical difference (delta)
    x_differences['delta'] = x_differences['self'] - x_differences['other']
    
    # Display the side-by-side comparison for the X column
    print("Detailed X Position Differences (Full Precision):")
    print(x_differences)

# Reset pandas display back to default when done
pd.reset_option('display.precision')

Found differences in 597 rows in the X position (p3_vx).

Rows with X differences: [1, 3, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 52, 53, 54, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609]

Detailed X Position Differences (Full Precision):
         self     other         delta
1    6.904348  6.904349 -1.000000e-06
3    1.561725  1.561726 -1.000000e-06
5   -4.369673 -4.369672 -1.000000e-06
7   -8.447906 -8.447905 -1.000000e-06
8   -9.212451 -9.212452  1.000000e-06
..        ...       ...           ...
605 -6.428946 -6.429281  3.350000e-04
606 -8.230558 -8.230806  2.480000e-04
607 -9.150779 -9.150905  1.260000e-04
608 -9.077529 -9.077494 -3.500000e-05
609 -7.997679 -7.997463 -2.160000e-04

[597 rows x 3 columns]

In [40]:
x_differences = heartbeat_from_begin['p3_vy'].compare(heartbeat_841['p3_vy'])

if x_differences.empty:
    print("No differences found in the X position. The files match perfectly!")
else:
    print(f"Found differences in {len(x_differences)} rows in the X position (p3_vy).\n")
    
    # List the rows where X values differ
    diff_row_indices = x_differences.index.tolist()
    print(f"Rows with X differences: {diff_row_indices}\n")
    
    # Add a column showing the exact mathematical difference (delta)
    x_differences['delta'] = x_differences['self'] - x_differences['other']
    
    # Display the side-by-side comparison for the X column
    print("Detailed X Position Differences (Full Precision):")
    print(x_differences)

# Reset pandas display back to default when done
pd.reset_option('display.precision')

Found differences in 592 rows in the X position (p3_vy).

Rows with X differences: [1, 2, 3, 5, 6, 7, 8, 12, 13, 14, 15, 18, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 41, 43, 44, 45, 46, 47, 48, 49, 50, 51, 55, 56, 57, 58, 59, 60, 61, 62, 63, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609]

Detailed X Position Differences (Full Precision):
         self     other         delta
1    6.218136  6.218134  2.000000e-06
2    8.111807  8.111806  1.000000e-06
3    9.100251  9.100250  1.000000e-06
5    8.102160  8.102161 -1.000000e-06
6    6.237111  6.237113 -2.000000e-06
..        ...       ...           ...
605  6.568347  6.568071  2.760000e-04
606  4.123004  4.122642  3.620000e-04
607  1.214658  1.214241  4.170000e-04
608 -1.854377 -1.854802  4.250000e-04
609 -4.753592 -4.753969  3.770000e-04

[592 rows x 3 columns]

In [41]:
x_differences = heartbeat_from_begin['p3_vz'].compare(heartbeat_841['p3_vz'])

if x_differences.empty:
    print("No differences found in the X position. The files match perfectly!")
else:
    print(f"Found differences in {len(x_differences)} rows in the X position (p3_vz).\n")
    
    # List the rows where X values differ
    diff_row_indices = x_differences.index.tolist()
    print(f"Rows with X differences: {diff_row_indices}\n")
    
    # Add a column showing the exact mathematical difference (delta)
    x_differences['delta'] = x_differences['self'] - x_differences['other']
    
    # Display the side-by-side comparison for the X column
    print("Detailed X Position Differences (Full Precision):")
    print(x_differences)

# Reset pandas display back to default when done
pd.reset_option('display.precision')

Found differences in 594 rows in the X position (p3_vz).

Rows with X differences: [1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 38, 39, 41, 43, 44, 45, 46, 47, 48, 49, 51, 52, 53, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 92, 93, 94, 95, 96, 97, 98, 99, 100, 102, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 117, 118, 121, 122, 123, 124, 125, 126, 127, 128, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609]

Detailed X Position Differences (Full Precision):
         self     other         delta
1   -0.038130 -0.038130  2.000000e-08
2   -0.004779 -0.004779  1.000000e-08
4    0.058981  0.058981 -3.000000e-08
5    0.082664  0.082664  1.000000e-08
6    0.097390  0.097390  3.000000e-08
..        ...       ...           ...
605  0.097997  0.098002 -5.570000e-06
606  0.103167  0.103172 -4.500000e-06
607  0.097178  0.097180 -2.450000e-06
608  0.080488  0.080488  7.000000e-08
609  0.054687  0.054685  2.440000e-06

[594 rows x 3 columns]